# Base Image
FROM node:22-alpine

RUN echo "======= Building Frontend ======="

CMD [ "echo", "Hello from the Frontend" ]

LABEL org.opencontainers.image.source=https://github.com/QuadcoreDevelopment/GHActions_Playground