# Base Image
FROM node:22-alpine

RUN echo "======= Building Backend v1.0.4 ======="

CMD [ "echo", "Hello from the Backend v1.0.4" ]

LABEL org.opencontainers.image.source=https://github.com/QuadcoreDevelopment/GHActions_Playground