# Base Image
FROM node:22-alpine

RUN echo "======= Building Backend ======="

CMD [ "echo", "Hello from the Backend" ]

LABEL org.opencontainers.image.source=https://github.com/QuadcoreDevelopment/GHActions_Playground